name: Build Android Registration-Client

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.4'

      - name: Install Dart SDK
        run: flutter pub get

      - name: Flutter clean
        run: flutter clean

      - name: Flutter test
        run: flutter test

      - name: Build Android APK
        run: flutter build apk